version: 2
updates:
  # shields.io dependencies
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily

  # badge-maker package dependencies
  - package-ecosystem: npm
    directory: '/badge-maker'
    schedule:
      interval: daily
      
  # close-bot package dependencies
  - package-ecosystem: npm
    directory: '/.github/actions/close-bot'
    schedule:
      interval: daily
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: daily
      
